# Generated by Django 2.2.4 on 2019-10-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtype',
            name='unit',
            field=models.CharField(default=' ', max_length=16, null=True),
        ),
    ]
